#spring.application.name=ProductService
#spring.jpa.hibernate.ddl-auto=update
#
#spring.datasource.url=jdbc:mysql://localhost:3306/productdb
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring:
  application:
    name: ProductService

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: root
    password: root

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}